[package]
name = "polynomials"
version = "0.1.0"
authors = ["IOHK"]
edition = "2018"

[dependencies.pairing]
version = "0.14.2"
features = ["u128-support"]

[dependencies]
merlin = "1.1.0"
rand = "0.4"
colored = "1.8"
rand_core = { version = "0.5" }
